bugDB/urls.py
from django.conf.urls import url, include
from .views import *

# URLs specific to the 'bugDB' app

urlpatterns = [
    url(r'^$', allIssuesView, name="all_issues"),
    url(r'^analytics/$', analytics, name="analytics"),
    url(r'^create/$', createTicket, name="create_issue"),
    url(r'^view-issue/(?P<id>[0-9]+)/$', issueDetailedView, name="detailed_view"),
    url(r'^edit-issue/(?P<id>[0-9]+)/$', editIssue, name="edit_issue"),
    url(r'^resolve-issue/(?P<id>[0-9]+)/$', resolveIssue, name="resolve_issue"),
    url(r'^reopen-issue/(?P<id>[0-9]+)/$', reOpenIssue, name="reopen_issue"),
    url(r'^close-issue/(?P<id>[0-9]+)/$', closeIssue, name="resolve_issue"),
    url(r'^up-vote/(?P<id>[0-9]+)/$', upVoteIssue, name="upvote_issue"),
]

bugTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("bugDB.urls")),
    url("accounts/", include("accounts.urls")),
    url("bug-tracker/", include("bugDB.urls")),
    url("make-payment/", include("makepayment.urls")),
    url("manage-projects/", include("projectManager.urls")),
    url("search/", include("search.urls")),
]

projectManager/urls.py
from django.conf.urls import url
from .views import *

# URLs specific to the 'projectManager' app

urlpatterns = [
    url(r'^$', viewProjects, name="view_projects"),
    url(r'^view/$', viewProjects, name="view_projects"),
    url(r'^add/$', createProject, name="add_project"),
    url(r'^edit/(?P<id>[0-9]+)/$', editProject, name="edit_project"),
    url(r'^delete/(?P<id>[0-9]+)/$', deleteProject, name="delete_project"),
]

projectManager/models.py
from django.db import models

# Model for issueProjects
class IssueProject(models.Model):

    projectName = models.CharField(max_length=30)

    def __str__(self):
        return "{}".format(self.projectName)

projectManager/forms.py
from django import forms
from django.forms import ModelForm
from .models import IssueProject

class IssueProjectForm(ModelForm):

    class Meta:
        model = IssueProject
        fields = ["projectName"]

projectManager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from .models import IssueProject
from .forms import IssueProjectForm

# view for showing all projects
@login_required
def viewProjects(request):

    projects = IssueProject.objects.all()

    return render(request, "project-manager/view-projects.html", {"projects": projects})

# View for creating new projects
@login_required
def createProject(request):

    # check if a post request is made
    if request.method == "POST":

        # create a new projectForm using POST data
        projectForm = IssueProjectForm(request.POST)

        # check if form is valid
        if projectForm.is_valid():

            # it's valid so save it
            projectForm.save()

            # give a success message and go back to the view projects page
            messages.success(request, "Project added successfully!")

            return redirect("view_projects")

        else:
            # form is not valid so send an error message and go back to view projects page
            messages.error(request, "Error: Unable to add Project!")

            return redirect("view_projects")
    else:
        # otherwise, return an empty form to view
        projectForm = IssueProjectForm()

        form = {"form": projectForm}
    
    return render(request, "project-manager/add-project.html", form)


# view for editing a project
@login_required
def editProject(request, id):
    # grab project by id
    project = get_object_or_404(IssueProject, pk=id)

    if request.method == "POST":
        # create a IssueProjectForm instance using post data
        updatedProject = IssueProjectForm(request.POST, instance=project)

        # check if data is valid
        if updatedProject.is_valid():
            # it's valid so go ahead and save
            updatedProject.save()

         # give a success message and go back to the view projects page
            messages.success(request, "Project updated successfully!")

            return redirect("view_projects")

        else:
            # form is not valid so send an error message and go back to view projects page
            messages.error(request, "Error: Unable to update Project!")

            return redirect("edit_project", id)
        

    return render(request, "project-manager/edit-project.html", {"form": IssueProjectForm(instance=project), "project": project})


# Handling the deleting of a project
@login_required
def deleteProject(request, id):
    # grab project instance
    project = get_object_or_404(IssueProject, pk=id)

    # go ahead & delete it from DB
    project.delete()

    # give a success message and go back to the view projects page
    messages.success(request, "Project deleted successfully!")
    
    return redirect("view_projects")

projectManager/templates/project-manager/add-project.html
{% extends "base.html" %}
{% block pageTitle %}Add Project{% endblock%}
{% block content%}
<div class="row">
    <h3 class="center-align">Add Project</h3>
</div>
<div class="row">
    <form action="{% url 'add_project' %}" method="POST" class="col s12">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <i class="material-icons prefix">apps</i>
                <input id="id_projectName" name="projectName" type="text" required>
                <label for="icon_prefix">Project Name</label>
            </div>
        </div>
        <div class="row center-align">
            <button class="btn waves-effect waves-light purple" type="submit">Add Project</button>
        </div>
    </form>
</div>
{% endblock %}

projectManager/templates/project-manager/edit-project.html
{% extends "base.html" %}
{% block pageTitle %}Edit Project{% endblock%}
{% block content%}
<div class="row">
    <h3 class="center-align">Edit Project</h3>
    <!-- Begin Edit Project Form -->
    <div class="row">
        <form action="{% url 'edit_project' project.id %}" method="POST" class="col s12">
            {% csrf_token %}
            
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">poll</i>
                    {{form.projectName}}
                    <!-- <input id="id_projectName" name="projectName" type="text" value="{{project.projectName}}" required> -->
                    <label for="icon_prefix">Project Name</label>
                </div>
            </div>
            <div class="row center-align">
                <button class="btn waves-effect waves-light purple" type="submit">Update Project</button>
            </div>
            {{ form.subject.errors }}
        </form>
    </div>
    <!-- End Edit Project Form -->
</div>
{% endblock %}

projectManager/templates/project-manager/view-projects.html
{% extends "base.html" %}
{% block pageTitle %}Manage Projects{% endblock%}
{% block content%}
<!-- Begin  Projects List-->
<div class="row">
    {% if projects %}
    <ul class="collapsible proj-collapsible">
        {% for project in projects %}
        <li>
            <div class="collapsible-header">
                <a href="{% url 'delete_project' project.id %}" class="waves-effect waves-light btn btn-small red">Del</a>
                <a href="{% url 'edit_project' project.id %}" class="waves-effect waves-light btn btn-small blue">Edit</a>
                <div class="category-title-header col s9">
                    <strong>{{project.projectName}}</strong>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="center-align">
        <h5>No Projects added yet. Click the button below to add one.</h5>
    </div>
    {% endif %}
</div>
<!-- End  Projects List-->
<!-- Begin Add Project Button-->
<div class="row center-align">
    <a href="{% url 'add_project' %}" class="waves-effect waves-light btn purple">Add New Project
        <i class="material-icons right">playlist_add</i>
    </a>
</div>
<!-- End Add Project Button-->
{% endblock %}